### ISSUE TITLE
Flutter Support

### ISSUE THREAD

**Issue by AppleEducate** [DirectMyFile/github.dart#138]
I know this is currently for web but how much of this is just pure dart and could support flutter?

I dont mind doing a PR.

**Comment by kirbyfan64** [comment]
This should also work on Flutter AFAIK, try following the parts of the docs labeled for the server side.

**Comment by AppleEducate** [comment]
Sweet!

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube

**Comment by buncismamen** [comment]
@AppleEducate if this is solved could you close this issue?

**Comment by AppleEducate** [comment]
I’ll check that out thank you!
