### ISSUE TITLE
api bug : pollEventsReceivedByUser

### ISSUE THREAD

**Issue by tk103331** [DirectMyFile/github.dart#143]
https://github.com/DirectMyFile/github.dart/blob/ca96181a098667b47fc1d35ee9e5acc70ddb718b/lib/src/common/activity_service.dart#L93

API Doc: 

![image](https://user-images.githubusercontent.com/4404609/59476592-0dcee180-8e84-11e9-8a80-544bb9ca1865.png)

![image](https://user-images.githubusercontent.com/4404609/59476650-4cfd3280-8e84-11e9-84d3-e3e7d21d7556.png)

**Comment by robbecker-wf** [comment]
This does seem like a straight up typo which results in this method returning the wrong events. Would you be up for making a PR that changes `events` to `received_events` @tk103331 ?

**Comment by robbecker-wf** [comment]
Thanks @tk103331 for reporting this. It is now fixed and will be in the 5.0.2 release.
