### ISSUE TITLE
Please publish latest on pub

### ISSUE THREAD

**Issue by Andersmholmgren** [DirectMyFile/github.dart#52]
I'm wanting the fix for https://github.com/DirectMyFile/github.dart/pull/50

thanks

**Comment by kaendfinger** [comment]
Ok, I'll publish in about an hour

**Comment by Andersmholmgren** [comment]
Thanks. Not seeing it in pub. Did you publish?

**Comment by kaendfinger** [comment]
Oh Sorry, one moment.

**Comment by kaendfinger** [comment]
Finally got it uploaded. Sorry I couldn't get it quicker, I was on a road trip this weekend and was unable to publish anything.

**Comment by Andersmholmgren** [comment]
Thanks and no worries
