### ISSUE TITLE
How to get an issue's comments?

### ISSUE THREAD

**Issue by mpgerlek** [DirectMyFile/github.dart#56]
How do I retrieve the comments for an issue?

I see there is a class named `IssueComment` and a property named `Issue.commentCount`, and so I expected to see something like `List<IssueComment> Issue.comments` but I'm not finding anything like that...

Hints?

**Comment by kaendfinger** [comment]
@mpgerlek Use this method. https://github.com/DirectMyFile/github.dart/blob/master/lib/src/common/issues_service.dart#L99

:) Thanks for using this library!

**Comment by mpgerlek** [comment]
Great, thank you!
