### ISSUE TITLE
SearchService lacks code and issue search support

### ISSUE THREAD

**Issue by ds84182** [DirectMyFile/github.dart#92]
Sure, there's some TODOs in search_service.dart, but it would be better to have an issue for this

- [x] SearchService Issue support
- [x] SearchService Code support

**Comment by robbecker-wf** [comment]
Closed via https://github.com/DirectMyFile/github.dart/pull/120 and https://github.com/DirectMyFile/github.dart/pull/170

**Comment by robbecker-wf** [comment]
To be released in 5.3.0
